#pragma checksum "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Layout\MainLayout.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "9612f8b0086834d92cd7d8e4765febd14baf89f5b7aa8f2661fcd1b380296439"
// <auto-generated/>
#pragma warning disable 1591
namespace KitchenSink.Client.Components.Layout
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1,2)-(1,23) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using System.Net.Http

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,28) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using System.Net.Http.Json

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,45) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,61) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using static Microsoft.AspNetCore.Components.Web.RenderMode

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,58) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,27) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,26) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using KitchenSink.Client

#nullable disable
    ;
#nullable restore
#line (10,2)-(10,37) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using KitchenSink.Client.Components

#nullable disable
    ;
#nullable restore
#line (11,2)-(11,44) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using KitchenSink.Client.Components.Layout

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class MainLayout : 
#nullable restore
#line (1,11)-(1,30) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Layout\MainLayout.razor"
LayoutComponentBase

#line default
#line hidden
#nullable disable

    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenElement(0, "div");
            __builder.AddAttribute(1, "class", "page");
            __builder.AddAttribute(2, "b-ym0hq95m43");
            __builder.OpenElement(3, "div");
            __builder.AddAttribute(4, "class", "sidebar");
            __builder.AddAttribute(5, "b-ym0hq95m43");
            __builder.OpenComponent<global::KitchenSink.Client.Components.Layout.NavMenu>(6);
            __builder.CloseComponent();
            __builder.CloseElement();
            __builder.AddMarkupContent(7, "\r\n\r\n    ");
            __builder.OpenElement(8, "main");
            __builder.AddAttribute(9, "b-ym0hq95m43");
            __builder.AddMarkupContent(10, "<div class=\"top-row px-4\" b-ym0hq95m43><a href=\"https://learn.microsoft.com/aspnet/core/\" target=\"_blank\" b-ym0hq95m43>About</a></div>\r\n\r\n        ");
            __builder.OpenElement(11, "article");
            __builder.AddAttribute(12, "class", "content px-4");
            __builder.AddAttribute(13, "b-ym0hq95m43");
#nullable restore
#line (14,14)-(14,18) 25 "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Layout\MainLayout.razor"
__builder.AddContent(14, Body

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.CloseElement();
            __builder.AddMarkupContent(15, "\r\n\r\n");
            __builder.AddMarkupContent(16, "<div id=\"blazor-error-ui\" data-nosnippet b-ym0hq95m43>\r\n    An unhandled error has occurred.\r\n    <a href=\".\" class=\"reload\" b-ym0hq95m43>Reload</a>\r\n    <span class=\"dismiss\" b-ym0hq95m43>🗙</span></div>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
