#pragma checksum "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Weather.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "f55e384a31948dec3d0179dbee0baec28445729ba410a124107b82fd08e55e80"
// <auto-generated/>
#pragma warning disable 1591
namespace KitchenSink.Client.Components.Pages
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1,2)-(1,23) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using System.Net.Http

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,28) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using System.Net.Http.Json

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,45) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,61) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using static Microsoft.AspNetCore.Components.Web.RenderMode

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,58) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,27) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,26) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using KitchenSink.Client

#nullable disable
    ;
#nullable restore
#line (10,2)-(10,37) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using KitchenSink.Client.Components

#nullable disable
    ;
#nullable restore
#line (11,2)-(11,44) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using KitchenSink.Client.Components.Layout

#nullable disable
    ;
    #line default
    #line hidden
    [global::Microsoft.AspNetCore.Components.RouteAttribute(
    // language=Route,Component
#nullable restore
#line (1,7)-(1,17) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Weather.razor"
"/weather"

#line default
#line hidden
#nullable disable
    )]
    #nullable restore
    public partial class Weather : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Microsoft.AspNetCore.Components.Web.PageTitle>(0);
            __builder.AddAttribute(1, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.AddContent(2, "Weather");
            }
            ));
            __builder.CloseComponent();
            __builder.AddMarkupContent(3, "\n\n");
            __builder.AddMarkupContent(4, "<h1>Weather</h1>\n\n");
            __builder.AddMarkupContent(5, "<p>This component demonstrates showing data.</p>");
#nullable restore
#line (10,2)-(12,1) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Weather.razor"
if (forecasts == null)
{

#line default
#line hidden
#nullable disable

            __builder.AddMarkupContent(6, "<p><em>Loading...</em></p>");
#nullable restore
#line (13,1)-(16,1) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Weather.razor"
}
else
{

#line default
#line hidden
#nullable disable

            __builder.OpenElement(7, "table");
            __builder.AddAttribute(8, "class", "table");
            __builder.AddMarkupContent(9, "<thead><tr><th>Date</th>\n                <th aria-label=\"Temperature in Celsius\">Temp. (C)</th>\n                <th aria-label=\"Temperature in Fahrenheit\">Temp. (F)</th>\n                <th>Summary</th></tr></thead>\n        ");
            __builder.OpenElement(10, "tbody");
#nullable restore
#line (26,1)-(26,13) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Weather.razor"
            

#line default
#line hidden
#nullable disable

#nullable restore
#line (26,14)-(28,1) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Weather.razor"
foreach (var forecast in forecasts)
            {

#line default
#line hidden
#nullable disable

            __builder.OpenElement(11, "tr");
            __builder.OpenElement(12, "td");
#nullable restore
#line (29,26)-(29,59) 25 "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Weather.razor"
__builder.AddContent(13, forecast.Date.ToShortDateString()

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(14, "\n                    ");
            __builder.OpenElement(15, "td");
#nullable restore
#line (30,26)-(30,47) 25 "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Weather.razor"
__builder.AddContent(16, forecast.TemperatureC

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(17, "\n                    ");
            __builder.OpenElement(18, "td");
#nullable restore
#line (31,26)-(31,47) 25 "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Weather.razor"
__builder.AddContent(19, forecast.TemperatureF

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(20, "\n                    ");
            __builder.OpenElement(21, "td");
#nullable restore
#line (32,26)-(32,42) 25 "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Weather.razor"
__builder.AddContent(22, forecast.Summary

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line (34,1)-(35,1) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Weather.razor"
            }

#line default
#line hidden
#nullable disable

            __builder.CloseElement();
            __builder.CloseElement();
#nullable restore
#line (37,1)-(38,1) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Weather.razor"
}

#line default
#line hidden
#nullable disable

        }
        #pragma warning restore 1998
#nullable restore
#line (39,8)-(46,1) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Weather.razor"

    private WeatherForecast[]? forecasts;

    protected override async Task OnInitializedAsync()
    {
        forecasts = await WeatherApi.GetForecastsAsync();
    }

#line default
#line hidden
#nullable disable

        [global::Microsoft.AspNetCore.Components.InjectAttribute] private 
#nullable restore
#line (2,9)-(2,20) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Weather.razor"
IWeatherApi

#line default
#line hidden
#nullable disable
         
#nullable restore
#line (2,21)-(2,31) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Weather.razor"
WeatherApi

#line default
#line hidden
#nullable disable
         { get; set; }
         = default!;
    }
}
#pragma warning restore 1591
