#pragma checksum "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\MarkupTitle.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "329dfb29934a7728ba5eef3b2a5c7a0dedf2aa549664f420a77c09f5d12cb9a3"
// <auto-generated/>
#pragma warning disable 1591
namespace KitchenSink.Client.Components.Pages
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1,2)-(1,23) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using System.Net.Http

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,28) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using System.Net.Http.Json

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,45) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,61) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using static Microsoft.AspNetCore.Components.Web.RenderMode

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,58) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,27) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,26) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using KitchenSink.Client

#nullable disable
    ;
#nullable restore
#line (10,2)-(10,37) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using KitchenSink.Client.Components

#nullable disable
    ;
#nullable restore
#line (11,2)-(11,44) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using KitchenSink.Client.Components.Layout

#nullable disable
    ;
#nullable restore
#line (12,2)-(12,33) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using KitchenSink.Client.Models

#nullable disable
    ;
#nullable restore
#line (13,2)-(13,31) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Razorshave.Abstractions

#nullable disable
    ;
    #line default
    #line hidden
    [global::Microsoft.AspNetCore.Components.RouteAttribute(
    // language=Route,Component
#nullable restore
#line (1,7)-(1,22) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\MarkupTitle.razor"
"/markup-title"

#line default
#line hidden
#nullable disable
    )]
    #nullable restore
    public partial class MarkupTitle : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Microsoft.AspNetCore.Components.Web.PageTitle>(0);
            __builder.AddAttribute(1, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.AddMarkupContent(2, "Verified — Public proof. €19/month.");
            }
            ));
            __builder.CloseComponent();
            __builder.AddMarkupContent(3, "\n\n");
            __builder.AddMarkupContent(4, "<h1>Markup-classified title test</h1>\n\n");
            __builder.AddMarkupContent(5, @"<p>This page exists to pin Razor's source-generator behaviour for static
   title text containing non-ASCII characters (em-dash, euro sign). The
   transpiler test fixture derived from this page locks down whether the
   SG routes the content through <code>AddContent</code> or
   <code>AddMarkupContent</code> — the runtime's PageTitle has to handle
   both shapes either way.</p>");
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
