#pragma checksum "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Counter.razor" "{8829d00f-11b8-4213-878b-770e8597ac16}" "c88f68436f0905ad5962f37d1b09a6ba8f9d848df76e998f10995a142c037619"
// <auto-generated/>
#pragma warning disable 1591
namespace KitchenSink.Client.Components.Pages
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1,2)-(1,23) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using System.Net.Http

#nullable disable
    ;
#nullable restore
#line (2,2)-(2,28) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using System.Net.Http.Json

#nullable disable
    ;
#nullable restore
#line (3,2)-(3,45) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Forms

#nullable disable
    ;
#nullable restore
#line (4,2)-(4,47) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Routing

#nullable disable
    ;
#nullable restore
#line (5,2)-(5,43) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web

#nullable disable
    ;
#nullable restore
#line (6,2)-(6,61) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using static Microsoft.AspNetCore.Components.Web.RenderMode

#nullable disable
    ;
#nullable restore
#line (7,2)-(7,58) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.AspNetCore.Components.Web.Virtualization

#nullable disable
    ;
#nullable restore
#line (8,2)-(8,27) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Microsoft.JSInterop

#nullable disable
    ;
#nullable restore
#line (9,2)-(9,26) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using KitchenSink.Client

#nullable disable
    ;
#nullable restore
#line (10,2)-(10,37) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using KitchenSink.Client.Components

#nullable disable
    ;
#nullable restore
#line (11,2)-(11,44) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using KitchenSink.Client.Components.Layout

#nullable disable
    ;
#nullable restore
#line (12,2)-(12,33) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using KitchenSink.Client.Models

#nullable disable
    ;
#nullable restore
#line (13,2)-(13,31) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\_Imports.razor"
using Razorshave.Abstractions

#nullable disable
    ;
    #line default
    #line hidden
    [global::Microsoft.AspNetCore.Components.RouteAttribute(
    // language=Route,Component
#nullable restore
#line (1,7)-(1,17) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Counter.razor"
"/counter"

#line default
#line hidden
#nullable disable
    )]
    [global::KitchenSink.Client.Components.Pages.Counter.__PrivateComponentRenderModeAttribute]
    #nullable restore
    public partial class Counter : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Microsoft.AspNetCore.Components.Web.PageTitle>(0);
            __builder.AddAttribute(1, "ChildContent", (global::Microsoft.AspNetCore.Components.RenderFragment)((__builder2) => {
                __builder2.AddContent(2, "Counter");
            }
            ));
            __builder.CloseComponent();
            __builder.AddMarkupContent(3, "\r\n\r\n");
            __builder.AddMarkupContent(4, "<h1>Counter</h1>\r\n\r\n");
            __builder.OpenElement(5, "p");
            __builder.AddAttribute(6, "role", "status");
            __builder.AddContent(7, "Current count: ");
#nullable restore
#line (8,34)-(8,46) 24 "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Counter.razor"
__builder.AddContent(8, currentCount

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
            __builder.AddMarkupContent(9, "\r\n\r\n");
            __builder.OpenElement(10, "button");
            __builder.AddAttribute(11, "class", "btn btn-primary");
            __builder.AddAttribute(12, "onclick", global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<global::Microsoft.AspNetCore.Components.Web.MouseEventArgs>(this, 
#nullable restore
#line (10,43)-(10,57) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Counter.razor"
IncrementCount

#line default
#line hidden
#nullable disable
            ));
            __builder.AddContent(13, "Click me");
            __builder.CloseElement();
        }
        #pragma warning restore 1998
#nullable restore
#line (12,8)-(20,1) "E:\Gewerbe\qsp\razorshave\e2e\KitchenSink.Client\Components\Pages\Counter.razor"

    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount++;
    }
    

#line default
#line hidden
#nullable disable

        private sealed class __PrivateComponentRenderModeAttribute : global::Microsoft.AspNetCore.Components.RenderModeAttribute
        {
            private static global::Microsoft.AspNetCore.Components.IComponentRenderMode ModeImpl => InteractiveServer
            ;
            public override global::Microsoft.AspNetCore.Components.IComponentRenderMode Mode => ModeImpl;
        }
    }
}
#pragma warning restore 1591
