using System.Collections.Immutable;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Diagnostics;

using Razorshave.Analyzer.Diagnostics;

namespace Razorshave.Analyzer;

/// <summary>
/// Fires <c>RZS2001</c> / <c>RZS2002</c> on C# expressions or statements
/// that the Razorshave transpiler cannot emit. Running this analyzer is
/// the difference between "silent <c>/* TODO */ null</c> in production JS
/// at runtime" and "red squiggle in the IDE at edit-time" — the whole
/// point is to make the unsupported path visible.
/// </summary>
/// <remarks>
/// <para>
/// The analyzer scopes itself to code inside a class that's either a Razor
/// component (<c>ComponentBase</c> / <c>LayoutComponentBase</c>) or marked
/// <c>[Client]</c>. Everything else (console apps, regular class libraries,
/// <c>Program.cs</c>) is left alone — those files aren't transpiled, so
/// flagging unsupported C# there would be noise.
/// </para>
/// <para>
/// Allowlist lives in <see cref="SupportedSyntax"/>. Adding a new case to
/// the transpiler's <c>ExpressionEmitter</c> or <c>StatementEmitter</c>
/// means adding the <see cref="SyntaxKind"/> there too — or the analyzer
/// will flag code the transpiler actually handles.
/// </para>
/// </remarks>
[DiagnosticAnalyzer(LanguageNames.CSharp)]
public sealed class UnsupportedLanguageFeatureAnalyzer : DiagnosticAnalyzer
{
    private static readonly DiagnosticDescriptor ExpressionRule = new(
        id: DiagnosticIds.UnsupportedExpression,
        title: "Unsupported C# expression in Razorshave code",
        messageFormat: "Razorshave cannot transpile '{0}' expressions yet — the transpiler will emit `null` at this location and the resulting JavaScript will not behave as intended",
        category: "Razorshave.Transpiler",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "The transpiler's ExpressionEmitter has no case for this syntax kind. Until one lands, rewrite the expression using a supported construct or move it out of a Razor component / [Client] class.");

    private static readonly DiagnosticDescriptor StatementRule = new(
        id: DiagnosticIds.UnsupportedStatement,
        title: "Unsupported C# statement in Razorshave code",
        messageFormat: "Razorshave cannot transpile '{0}' statements yet — the transpiler will emit a TODO comment at this location and downstream behaviour will break",
        category: "Razorshave.Transpiler",
        defaultSeverity: DiagnosticSeverity.Error,
        isEnabledByDefault: true,
        description: "The transpiler's StatementEmitter has no case for this syntax kind. Until one lands, restructure the method with supported statements (if/else, for, foreach, local-declaration, expression, return).");

    public override ImmutableArray<DiagnosticDescriptor> SupportedDiagnostics =>
        ImmutableArray.Create(ExpressionRule, StatementRule);

    public override void Initialize(AnalysisContext context)
    {
        // Razor compiles `.razor` → `.razor.g.cs` with an <auto-generated> header,
        // which Roslyn marks as generated. With the default `None`, @code blocks
        // slip past the analyzer entirely. We opt in so Razor components get
        // checked; the IsRazorshaveTranspileTarget filter already keeps hand-rolled
        // `.g.cs` (InternalsVisibleTo, GlobalUsings, etc.) out of scope.
        // Both flags are needed: Analyze runs the analyzer on generated code,
        // ReportDiagnostics lets the resulting diagnostics actually surface.
        context.ConfigureGeneratedCodeAnalysis(
            GeneratedCodeAnalysisFlags.Analyze | GeneratedCodeAnalysisFlags.ReportDiagnostics);
        context.EnableConcurrentExecution();
        context.RegisterSymbolAction(AnalyzeClass, SymbolKind.NamedType);
    }

    // Class names that the build pipeline skips: Routes.razor is special-cased
    // (its Router is replaced by the runtime router), App.razor is the server
    // host document, Error.razor is the Blazor-server error page (HttpContext /
    // Activity — server-only). None of them reach the transpiler, so flagging
    // their @code blocks is pure noise.
    private static readonly HashSet<string> SkippedComponentNames = new(StringComparer.Ordinal)
    {
        "Routes", "App", "Error",
    };

    private static void AnalyzeClass(SymbolAnalysisContext context)
    {
        if (context.Symbol is not INamedTypeSymbol type) return;
        if (!IsRazorshaveTranspileTarget(type)) return;
        if (SkippedComponentNames.Contains(type.Name)) return;

        foreach (var syntaxRef in type.DeclaringSyntaxReferences)
        {
            var node = syntaxRef.GetSyntax(context.CancellationToken);
            if (node is not ClassDeclarationSyntax classNode) continue;
            AnalyzeClassBody(classNode, context);
        }
    }

    // Walks every expression and statement inside the class body, checking
    // each syntax kind against the supported set. Analyzer actions run per
    // class, so we only visit members that can actually end up in the
    // transpiled output.
    private static void AnalyzeClassBody(ClassDeclarationSyntax classNode, SymbolAnalysisContext context)
    {
        foreach (var descendant in classNode.DescendantNodes())
        {
            context.CancellationToken.ThrowIfCancellationRequested();

            if (descendant is ExpressionSyntax expr)
            {
                var kind = expr.Kind();
                if (IgnoredExpressionKind(kind)) continue;
                if (!SupportedSyntax.Expressions.Contains(kind))
                {
                    var location = expr.GetLocation();
                    if (IsRazorGeneratorInternal(location)) continue;
                    context.ReportDiagnostic(Diagnostic.Create(
                        ExpressionRule, location, kind.ToString()));
                }
            }
            else if (descendant is StatementSyntax stmt)
            {
                var kind = stmt.Kind();
                if (!SupportedSyntax.Statements.Contains(kind))
                {
                    var location = stmt.GetLocation();
                    if (IsRazorGeneratorInternal(location)) continue;
                    context.ReportDiagnostic(Diagnostic.Create(
                        StatementRule, location, kind.ToString()));
                }
            }
        }
    }

    // True when the node sits in Razor-generator-emitted machinery rather than
    // user @code. Razor emits `#line` pragmas pointing back to the original
    // `.razor` for user code; generator-internal scaffolding (BuildRenderTree
    // helpers, nullable-suppression casts on typed attribute values) has no
    // mapping, so GetMappedLineSpan() returns the `.g.cs` path unchanged.
    // Filtering here instead of in the walker keeps the IgnoredExpressionKind
    // table focused on language shape, not on where the node came from.
    private static bool IsRazorGeneratorInternal(Location location)
    {
        var span = location.GetMappedLineSpan();
        if (!span.IsValid) return false;
        var path = span.Path;
        // #line-mapped back to .razor → real user code; analyze it.
        if (path.EndsWith(".razor", StringComparison.OrdinalIgnoreCase)) return false;
        // No mapping — the node is in the generated `.g.cs` scaffolding itself.
        return path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase);
    }

    // Kinds that syntactically show up as ExpressionSyntax but either don't
    // reach the emitter (attribute arguments, pattern-internals) or are
    // covered by a dedicated emitter path we don't need the allowlist to
    // second-guess.
    private static bool IgnoredExpressionKind(SyntaxKind kind) => kind switch
    {
        // SyntaxKind ancillaries that appear as expression sub-nodes.
        SyntaxKind.IdentifierName => true,
        SyntaxKind.GenericName => true,
        SyntaxKind.AliasQualifiedName => true,
        SyntaxKind.QualifiedName => true,
        // Type annotations (`int`, `string?`, `List<T>`, `int[]`, `(int, string)`)
        // descend from ExpressionSyntax in Roslyn's grammar but aren't emitted
        // as JS — they're metadata on the declaration they belong to. Flagging
        // them would fire on every variable declaration of a complex type.
        SyntaxKind.NullableType => true,
        SyntaxKind.ArrayType => true,
        SyntaxKind.PointerType => true,
        SyntaxKind.RefType => true,
        SyntaxKind.TupleType => true,
        // `int[]` array-type rank-specifiers contain `OmittedArraySizeExpression`
        // placeholders that never render — they're part of the type shape.
        SyntaxKind.OmittedArraySizeExpression => true,
        _ => false,
    };

    private static bool IsRazorshaveTranspileTarget(INamedTypeSymbol type)
    {
        // [Client]-marked classes are transpiled as-is.
        foreach (var attr in type.GetAttributes())
        {
            var name = attr.AttributeClass?.Name;
            if (name == "ClientAttribute" || name == "Client") return true;
        }
        // Razor components: any ancestor is ComponentBase or LayoutComponentBase.
        for (var baseSym = type.BaseType; baseSym is not null; baseSym = baseSym.BaseType)
        {
            if (baseSym.Name is "ComponentBase" or "LayoutComponentBase") return true;
        }
        return false;
    }
}
